id: tas-ArT7lw8y
type: task
title: Publish to NPM
status: todo
createdAt: 2026-02-19T18:52:30.049Z
updatedAt: 2026-02-19T18:52:30.049Z
description: Oh no is it finally time!?
assignee: use-JTYCH2se
sprint: spr-hDifgOv0
priority: low
estimate: 5
